### ISSUE TITLE
Add Link to Repo

### ISSUE THREAD

**Issue by geyang** [datastructures-js/datastructures-js.github.io#1]
I sugguest adding a README. Also add [the link](https://datastructures-js.github.io/) to the project description to the right: 

<img width="565" alt="Screenshot 2024-07-09 at 2 16 23 PM" src="https://github.com/datastructures-js/datastructures-js.github.io/assets/630490/979359c2-0603-4ca1-9d46-b9ae7b150453">

**Comment by eyas-ranjous** [comment]
added
